### ISSUE TITLE
fs not found

### ISSUE THREAD

**Issue by wangsai-silence** [SalvatorePreviti/roaring-wasm#11]
```
Module not found: Error: Can't resolve 'fs' in './node_modules/roaring-wasm/lib/roaring-wasm'
ERROR in ./node_modules/roaring-wasm/lib/roaring-wasm/roaring-wasm-module.js 50:16-29

```

How can I use this lib with webpack

**Comment by SalvatorePreviti** [comment]
I am working on a new release that would work in browser and node as well. The project was not updated for long time and never fully completed or tested in browser. Will let you know when the new version will be released

**Comment by SalvatorePreviti** [comment]
Solved in the new version of roaring-wasm that works also in browser
