### ISSUE TITLE
RoaringBitmap32 toString() currently unimplemented? 

### ISSUE THREAD

**Issue by lemire** [SalvatorePreviti/roaring-wasm#3]
It seems that we can't get a string representation of a RoaringBitmap32 object by calling toString(). Of course, if we had iterators, this could be implemented well.  With iterators, something like this might be possible...

https://github.com/RoaringBitmap/gocroaring/blob/master/gocroaring.go#L313-L333

**Comment by SalvatorePreviti** [comment]
Correct, still not implemented, it increases by a lot the WASM size (it would need to include printf and C++ strings to just use the default implementation). Would make sense to write a custom implementation after iterators are implemented directly in JS.

**Comment by lemire** [comment]
> Would make sense to write a custom implementation after iterators are implemented directly in JS.

Right, see again ...

https://github.com/RoaringBitmap/gocroaring/blob/master/gocroaring.go#L313-L333

**Comment by SalvatorePreviti** [comment]
implemented the join, joinSlice, joinRange methods
