### ISSUE TITLE
TypeScript error: no-void-expression  Expression has type `void`. Put it on its own line as a statement.

### ISSUE THREAD

**Issue by lemire** [SalvatorePreviti/roaring-wasm#6]
> ▪ compile typescript ...
> roaring-wasm/test/unit/RoaringUint8Array.test.ts:130:19
> ERROR: 130:19  no-void-expression  Expression has type `void`. Put it on its own line as a statement.
> 
> ✖ compile typescript: Failed.

The line in question is...

>     expect(() => t.throwIfDisposed()).toThrow()

**Comment by SalvatorePreviti** [comment]
Could not reproduced but fixed the issue.
